CREATE DATABASE IF NOT EXISTS paytm_userauthdb    CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS paytm_walletdb      CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS paytm_transactiondb CHARACTER SET utf8mb4;