name: CI - Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.3
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Wait for MySQL and create the three schemas the apps expect
      - name: Create databases
        run: |
          sudo apt-get update && sudo apt-get install -y mysql-client
          for i in {1..20}; do
            if mysqladmin ping -h 127.0.0.1 --silent; then break; fi
            echo "Waiting for MySQL ..."; sleep 3
          done
          mysql -h 127.0.0.1 -uroot -p${{ secrets.MYSQL_ROOT_PASSWORD }} \
            -e "CREATE DATABASE IF NOT EXISTS paytm_userauthdb;"
          mysql -h 127.0.0.1 -uroot -p${{ secrets.MYSQL_ROOT_PASSWORD }} \
            -e "CREATE DATABASE IF NOT EXISTS paytm_walletdb;"
          mysql -h 127.0.0.1 -uroot -p${{ secrets.MYSQL_ROOT_PASSWORD }} \
            -e "CREATE DATABASE IF NOT EXISTS paytm_transactiondb;"

      # Build user‑auth‑service
      - name: Build user‑auth‑service
        working-directory: User-auth-service
        run: |
          chmod +x mvnw
          ./mvnw -B clean verify
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/paytm_userauthdb
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

      # Build wallet‑service
      - name: Build wallet‑service
        working-directory: Wallet-service
        run: |
          chmod +x mvnw
          ./mvnw -B clean verify
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/paytm_walletdb
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

      # Build transaction‑service
      - name: Build transaction‑service
        working-directory: Transaction-Service
        run: |
          chmod +x mvnw
          ./mvnw -B clean verify
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/paytm_transactiondb
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          WALLET_BASE_URL: http://localhost:8083
