name: CI - Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.3
        env:
          MYSQL_ROOT_PASSWORD: Rawatbhata1@
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build User-auth-service
        working-directory: User-auth-service
        run: |
          chmod +x mvnw
          ./mvnw -B clean verify
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/paytm_userauthdb
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: Rawatbhata1@

      - name: Build Wallet-service
        working-directory: Wallet-service
        run: |
          chmod +x mvnw
          ./mvnw -B clean verify
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/paytm_walletdb
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: Rawatbhata1@

      - name: Build Transaction-Service
        working-directory: Transaction-Service
        run: |
          chmod +x mvnw
          ./mvnw -B clean verify
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/paytm_transactiondb
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: Rawatbhata1@
          WALLET_BASE_URL: http://localhost:8083
